### ISSUE TITLE
How does it exactly work ?

### ISSUE THREAD

**Issue by akisatu** [Bill4Time/mongo-fast-join#10]
Hi, I don't know if this project is still alive, but I would like to understand how you achieved this join query if it doesn't bother you ?
Well, I'm quite new to MongoDB, but I thought that joins were not possible. Furthermore, are your joins compiled server-side or client side and if it is client-side, how many times do you call the server ?

Thank you for your answer.

**Comment by khous** [comment]
I'm not maintaining this anymore. The joins are accomplished client side. A
join is a pretty simple concept to code. So that's what this project does.
If you understand how joins work, that's how I'm doing it. I went to
extremes working around mongo's limitations and this is how I achieved
better performance with the version of the day. It calls the server a lot,
so it would be ideal if your ween server was coo located with the db sever.
Better yet is to avoid joins altogether or use a database more suitable to
your requirements.

**Comment by akisatu** [comment]
Okay thank you, I understand now.
